services:
  # Python Backend
  - type: web
    name: kasparro-backend
    env: python
    region: singapore # Close to ap-south-1
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python create_tables.py && uvicorn api.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: API_KEY
        value: testkey
      - key: DATABASE_URL
        fromDatabase:
          name: kasparro-db
          property: connectionString

databases:
  # Postgres DB
  - name: kasparro-db
    region: singapore
    plan: free # 90 days free
